### ISSUE TITLE
Issue with sxs.load

### ISSUE THREAD

**Issue by gcompere** [moble/sxs_notebooks#2]
Hi, 
I ran the tutorial notebook on waveforms but the command 
sxs.load("SXS:BBH:1108/Lev/rhOverM", extrapolation_order=extrapolation_order, progress=False)
gives me the error
"An error occurred when trying to access <https://zenodo.org/api/files/1a7cd5b5-d96f-4208-b72c-b0dd5354ba29/Lev5/rhOverM_Asymptotic_GeometricUnits_CoM.h5>.
{'message': 'The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'status': 404}"

I have the latest version of python, tqdm, jupyter. I was not able to install sxs-ecosystem (not listed on PyPI). 

I noticed that a similar error was mentionned in 2021 and solved by adding discarding the use of tqdm by setting (Progress-> False), but it does not help in my case. 

Thank you for your precious help!

**Comment by moble** [comment]
Yeah, sorry about this.  Zenodo recently overhauled their API and changed the URL.  I'm working on the fix, but it's taking longer than expected.  Follow this issue for updates:  sxs-collaboration/sxs#81
